// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAok1qXHazGTZBREN0VJWOAHJW8_I1HFEE',
    appId: '1:420636499043:web:ed52229df77c1c39bd6c56',
    messagingSenderId: '420636499043',
    projectId: 'ciclofit-dev',
    authDomain: 'ciclofit-dev.firebaseapp.com',
    storageBucket: 'ciclofit-dev.firebasestorage.app',
    measurementId: 'G-HMRFGD85EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjlYlWQ2RsuIEb3OQY4iY7Eh0snIKYIWw',
    appId: '1:420636499043:android:8b51ebfdd5cafebbbd6c56',
    messagingSenderId: '420636499043',
    projectId: 'ciclofit-dev',
    storageBucket: 'ciclofit-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdB9s9D5B3aSb0d99wgTgRuLerzKEZfE',
    appId: '1:420636499043:ios:9cb271069e3bc31cbd6c56',
    messagingSenderId: '420636499043',
    projectId: 'ciclofit-dev',
    storageBucket: 'ciclofit-dev.firebasestorage.app',
    iosClientId:
        '420636499043-fqpn5ugph1nise7s0ahg533s9nknl3fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdB9s9D5B3aSb0d99wgTgRuLerzKEZfE',
    appId: '1:420636499043:ios:9cb271069e3bc31cbd6c56',
    messagingSenderId: '420636499043',
    projectId: 'ciclofit-dev',
    storageBucket: 'ciclofit-dev.firebasestorage.app',
    iosClientId:
        '420636499043-fqpn5ugph1nise7s0ahg533s9nknl3fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAok1qXHazGTZBREN0VJWOAHJW8_I1HFEE',
    appId: '1:420636499043:web:aa391a150015744cbd6c56',
    messagingSenderId: '420636499043',
    projectId: 'ciclofit-dev',
    authDomain: 'ciclofit-dev.firebaseapp.com',
    storageBucket: 'ciclofit-dev.firebasestorage.app',
    measurementId: 'G-T43KXV9NED',
  );
}
